// @ts-check
/**
 * Tests for AIP OpenAPI Discovery CLI
 * Run with: node --test src/discover.test.js
 */

import { describe, it, before, after, beforeEach } from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  findSpecFiles,
  looksLikeSpec,
  detectGenerated,
  analyzeSpec,
  formatMarkdown,
  formatJSON,
  main,
  GLOB_PATTERNS,
  DEFAULT_IGNORES,
} from './discover.js';

/**
 * @typedef {import('./discover.js').DiscoveryResult} DiscoveryResult
 * @typedef {import('./discover.js').SpecInfo} SpecInfo
 */

/**
 * Helper to create test SpecInfo
 * @param {Partial<SpecInfo>} overrides
 * @returns {SpecInfo}
 */
function createSpecInfo(overrides = {}) {
  return {
    path: 'api.yaml',
    absolutePath: '/test/api.yaml',
    filename: 'api.yaml',
    type: /** @type {const} */ ('openapi-3.x'),
    version: '3.0.0',
    title: 'Test API',
    apiVersion: '1.0.0',
    pathCount: 2,
    operationCount: 3,
    isGenerated: false,
    ...overrides,
  };
}

/**
 * Helper to create test DiscoveryResult
 * @param {Partial<DiscoveryResult>} overrides
 * @returns {DiscoveryResult}
 */
function createDiscoveryResult(overrides = {}) {
  return {
    searchPath: '/test',
    discoveredAt: '2024-01-01T00:00:00.000Z',
    specs: [createSpecInfo()],
    summary: { total: 1, openapi3: 1, swagger2: 0, parseErrors: 0 },
    ...overrides,
  };
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURES_DIR = join(__dirname, '__fixtures__');

// ============================================
// looksLikeSpec Tests
// ============================================

describe('looksLikeSpec', () => {
  it('detects openapi YAML key', () => {
    assert.equal(looksLikeSpec('openapi: 3.0.0'), true);
  });

  it('detects openapi JSON key', () => {
    assert.equal(looksLikeSpec('{"openapi": "3.0.0"}'), true);
  });

  it('detects swagger YAML key', () => {
    assert.equal(looksLikeSpec('swagger: "2.0"'), true);
  });

  it('detects swagger JSON key', () => {
    assert.equal(looksLikeSpec('{"swagger": "2.0"}'), true);
  });

  it('rejects non-spec content', () => {
    assert.equal(looksLikeSpec('name: some-config\nvalue: 123'), false);
  });

  it('rejects empty content', () => {
    assert.equal(looksLikeSpec(''), false);
  });
});

// ============================================
// detectGenerated Tests
// ============================================

describe('detectGenerated', () => {
  it('detects "Generated by" comment', () => {
    const content = '# Generated by openapi-generator\nopenapi: 3.0.0';
    const result = detectGenerated(content);
    assert.equal(result.isGenerated, true);
    assert.ok(result.comment?.includes('Generated by'));
  });

  it('detects "DO NOT EDIT" comment', () => {
    const content = '// DO NOT EDIT - auto-generated\nopenapi: 3.0.0';
    const result = detectGenerated(content);
    assert.equal(result.isGenerated, true);
  });

  it('detects x-generator extension', () => {
    const content = 'openapi: 3.0.0\nx-generator: swagger-codegen';
    const result = detectGenerated(content);
    assert.equal(result.isGenerated, true);
  });

  it('detects JSON x-generator', () => {
    const content = '{"openapi": "3.0.0", "x-generator": "openapi-gen"}';
    const result = detectGenerated(content);
    assert.equal(result.isGenerated, true);
  });

  it('detects Auto-generated comment', () => {
    const content = '<!-- Auto-generated API spec -->\nopenapi: 3.0.0';
    const result = detectGenerated(content);
    assert.equal(result.isGenerated, true);
  });

  it('returns false for hand-written specs', () => {
    const content = 'openapi: 3.0.0\ninfo:\n  title: My API';
    const result = detectGenerated(content);
    assert.equal(result.isGenerated, false);
    assert.equal(result.comment, undefined);
  });
});

// ============================================
// formatJSON Tests
// ============================================

describe('formatJSON', () => {
  it('outputs valid JSON', () => {
    const result = {
      searchPath: '/test',
      discoveredAt: '2024-01-01T00:00:00.000Z',
      specs: [],
      summary: { total: 0, openapi3: 0, swagger2: 0, parseErrors: 0 },
    };
    const output = formatJSON(result);
    const parsed = JSON.parse(output);
    assert.equal(parsed.searchPath, '/test');
  });

  it('includes spec details', () => {
    const result = createDiscoveryResult();
    const output = formatJSON(result);
    const parsed = JSON.parse(output);
    assert.equal(parsed.specs[0].title, 'Test API');
  });
});

// ============================================
// formatMarkdown Tests
// ============================================

describe('formatMarkdown', () => {
  it('includes frontmatter', () => {
    const result = {
      searchPath: '/test',
      discoveredAt: '2024-01-01T00:00:00.000Z',
      specs: [],
      summary: { total: 0, openapi3: 0, swagger2: 0, parseErrors: 0 },
    };
    const output = formatMarkdown(result);
    assert.ok(output.startsWith('---'));
    assert.ok(output.includes('discovered_by: aip-discover'));
  });

  it('includes summary table', () => {
    const result = {
      searchPath: '/test',
      discoveredAt: '2024-01-01T00:00:00.000Z',
      specs: [],
      summary: { total: 5, openapi3: 3, swagger2: 2, parseErrors: 0 },
    };
    const output = formatMarkdown(result);
    assert.ok(output.includes('| OpenAPI 3.x | 3 |'));
    assert.ok(output.includes('| Swagger 2.x | 2 |'));
    assert.ok(output.includes('| **Total** | **5** |'));
  });

  it('shows "No Specifications Found" when empty', () => {
    const result = {
      searchPath: '/test',
      discoveredAt: '2024-01-01T00:00:00.000Z',
      specs: [],
      summary: { total: 0, openapi3: 0, swagger2: 0, parseErrors: 0 },
    };
    const output = formatMarkdown(result);
    assert.ok(output.includes('No Specifications Found'));
  });

  it('lists spec details', () => {
    const result = createDiscoveryResult({
      specs: [
        createSpecInfo({
          title: 'My Test API',
          pathCount: 2,
          operationCount: 3,
          servers: ['https://api.example.com'],
          tags: ['users', 'orders'],
        }),
      ],
    });
    const output = formatMarkdown(result);
    assert.ok(output.includes('### My Test API'));
    assert.ok(output.includes('**Path:** `api.yaml`'));
    assert.ok(output.includes('**Paths:** 2'));
    assert.ok(output.includes('**Operations:** 3'));
    assert.ok(output.includes('**Servers:** https://api.example.com'));
    assert.ok(output.includes('**Tags:** users, orders'));
  });

  it('shows parse errors', () => {
    const result = createDiscoveryResult({
      specs: [
        createSpecInfo({
          path: 'bad.yaml',
          absolutePath: '/test/bad.yaml',
          filename: 'bad.yaml',
          type: /** @type {const} */ ('unknown'),
          version: '',
          title: '',
          apiVersion: '',
          pathCount: 0,
          operationCount: 0,
          error: new Error('Invalid spec'),
        }),
      ],
      summary: { total: 1, openapi3: 0, swagger2: 0, parseErrors: 1 },
    });
    const output = formatMarkdown(result);
    assert.ok(output.includes('**Status:** Parse Error'));
    assert.ok(output.includes('Invalid spec'));
  });

  it('shows generated indicator', () => {
    const result = createDiscoveryResult({
      specs: [
        createSpecInfo({
          title: 'Generated API',
          pathCount: 0,
          operationCount: 0,
          isGenerated: true,
          generatorComment: '# Generated by swagger-codegen',
        }),
      ],
    });
    const output = formatMarkdown(result);
    assert.ok(output.includes('**Generated:** Yes'));
    assert.ok(output.includes('swagger-codegen'));
  });

  it('includes next steps with /api-review command', () => {
    const result = createDiscoveryResult({
      specs: [
        createSpecInfo({
          path: 'openapi.yaml',
          absolutePath: '/test/openapi.yaml',
          filename: 'openapi.yaml',
          title: 'API',
          pathCount: 1,
          operationCount: 1,
        }),
      ],
    });
    const output = formatMarkdown(result);
    assert.ok(output.includes('/api-review openapi.yaml'));
  });
});

// ============================================
// findSpecFiles Tests
// ============================================

describe('findSpecFiles', () => {
  const TEMP_DIR = join(__dirname, '__temp_test__');

  before(() => {
    // Create temp directory structure
    mkdirSync(TEMP_DIR, { recursive: true });
    mkdirSync(join(TEMP_DIR, 'api'), { recursive: true });
    mkdirSync(join(TEMP_DIR, 'docs'), { recursive: true });
    mkdirSync(join(TEMP_DIR, 'node_modules', 'some-pkg'), { recursive: true });
    mkdirSync(join(TEMP_DIR, 'nested', 'deep'), { recursive: true });

    // Create spec files
    writeFileSync(join(TEMP_DIR, 'openapi.yaml'), 'openapi: 3.0.0');
    writeFileSync(join(TEMP_DIR, 'api', 'swagger.json'), '{"swagger": "2.0"}');
    writeFileSync(join(TEMP_DIR, 'docs', 'api.yml'), 'openapi: 3.0.0');
    writeFileSync(
      join(TEMP_DIR, 'nested', 'deep', 'openapi.json'),
      '{"openapi": "3.0.0"}'
    );

    // Create non-spec files (should not be found)
    writeFileSync(join(TEMP_DIR, 'readme.md'), '# Readme');
    writeFileSync(join(TEMP_DIR, 'config.yaml'), 'name: config');

    // File in node_modules (should be skipped by glob exclude)
    writeFileSync(
      join(TEMP_DIR, 'node_modules', 'some-pkg', 'openapi.yaml'),
      'openapi: 3.0.0'
    );
  });

  after(() => {
    rmSync(TEMP_DIR, { recursive: true, force: true });
  });

  it('finds spec files in root directory', async () => {
    const files = await findSpecFiles(TEMP_DIR);
    const filenames = files.map((f) => f.split('/').pop());
    assert.ok(filenames.includes('openapi.yaml'));
  });

  it('finds spec files in subdirectories', async () => {
    const files = await findSpecFiles(TEMP_DIR);
    const filenames = files.map((f) => f.split('/').pop());
    assert.ok(filenames.includes('swagger.json'));
    assert.ok(filenames.includes('api.yml'));
  });

  it('finds deeply nested spec files', async () => {
    const files = await findSpecFiles(TEMP_DIR);
    const filenames = files.map((f) => f.split('/').pop());
    assert.ok(filenames.includes('openapi.json'));
  });

  it('skips node_modules directory', async () => {
    const files = await findSpecFiles(TEMP_DIR);
    const inNodeModules = files.some((f) => f.includes('node_modules'));
    assert.equal(inNodeModules, false);
  });

  it('ignores non-spec yaml/json files', async () => {
    const files = await findSpecFiles(TEMP_DIR);
    const hasConfig = files.some((f) => f.includes('config.yaml'));
    assert.equal(hasConfig, false);
  });

  it('returns empty array for non-existent directory', async () => {
    const files = await findSpecFiles('/nonexistent/path/that/does/not/exist');
    assert.equal(files.length, 0);
  });
});

// ============================================
// Constants Tests
// ============================================

describe('GLOB_PATTERNS', () => {
  it('includes openapi patterns', () => {
    const hasOpenapi = GLOB_PATTERNS.some((p) => p.includes('openapi'));
    assert.ok(hasOpenapi);
  });

  it('includes swagger patterns', () => {
    const hasSwagger = GLOB_PATTERNS.some((p) => p.includes('swagger'));
    assert.ok(hasSwagger);
  });

  it('includes yaml and json extensions', () => {
    const hasYaml = GLOB_PATTERNS.some((p) => p.includes('yaml'));
    const hasJson = GLOB_PATTERNS.some((p) => p.includes('json'));
    assert.ok(hasYaml);
    assert.ok(hasJson);
  });
});

describe('DEFAULT_IGNORES', () => {
  it('includes node_modules', () => {
    const hasNodeModules = DEFAULT_IGNORES.some((p) =>
      p.includes('node_modules')
    );
    assert.ok(hasNodeModules);
  });

  it('includes .git', () => {
    const hasGit = DEFAULT_IGNORES.some((p) => p.includes('.git'));
    assert.ok(hasGit);
  });

  it('includes dist and build', () => {
    const hasDist = DEFAULT_IGNORES.some((p) => p.includes('dist'));
    const hasBuild = DEFAULT_IGNORES.some((p) => p.includes('build'));
    assert.ok(hasDist);
    assert.ok(hasBuild);
  });
});

// ============================================
// analyzeSpec Tests
// ============================================

describe('analyzeSpec', () => {
  it('parses valid OpenAPI 3.x spec', async () => {
    const specPath = join(FIXTURES_DIR, 'valid-openapi3.yaml');
    const info = await analyzeSpec(specPath, FIXTURES_DIR);

    assert.equal(info.filename, 'valid-openapi3.yaml');
    assert.equal(info.type, 'openapi-3.x');
    assert.equal(info.version, '3.0.3');
    assert.equal(info.title, 'Test API');
    assert.equal(info.apiVersion, '1.0.0');
    assert.equal(info.pathCount, 2);
    assert.ok(info.operationCount >= 2);
    assert.ok(info.servers?.includes('https://api.example.com'));
    assert.ok(info.tags?.includes('users'));
    assert.equal(info.isGenerated, false);
    assert.equal(info.error, undefined);
  });

  it('parses valid Swagger 2.x spec', async () => {
    const specPath = join(FIXTURES_DIR, 'valid-swagger2.json');
    const info = await analyzeSpec(specPath, FIXTURES_DIR);

    assert.equal(info.type, 'swagger-2.x');
    assert.equal(info.version, '2.0');
    assert.equal(info.title, 'Swagger Test API');
    assert.equal(info.apiVersion, '2.0.0');
    assert.equal(info.pathCount, 1);
    assert.equal(info.error, undefined);
  });

  it('detects generated spec', async () => {
    const specPath = join(FIXTURES_DIR, 'generated-spec.yaml');
    const info = await analyzeSpec(specPath, FIXTURES_DIR);

    assert.equal(info.isGenerated, true);
    assert.ok(info.generatorComment?.includes('Generated by'));
  });

  it('returns error for non-spec file', async () => {
    const specPath = join(FIXTURES_DIR, 'not-a-spec.yaml');
    const info = await analyzeSpec(specPath, FIXTURES_DIR);

    assert.equal(info.type, 'unknown');
    assert.ok(info.error);
    assert.ok(info.error.message.includes('does not appear to be'));
  });

  it('handles invalid spec gracefully', async () => {
    const specPath = join(FIXTURES_DIR, 'invalid-spec.yaml');
    const info = await analyzeSpec(specPath, FIXTURES_DIR);

    // Should have parsed but may have validation error
    assert.equal(info.filename, 'invalid-spec.yaml');
    // The spec is invalid (missing title), so should have an error
    assert.ok(info.error);
  });

  it('sets relative path correctly', async () => {
    const specPath = join(FIXTURES_DIR, 'valid-openapi3.yaml');
    const info = await analyzeSpec(specPath, FIXTURES_DIR);

    assert.equal(info.path, 'valid-openapi3.yaml');
    assert.equal(info.absolutePath, specPath);
  });
});

// ============================================
// main() CLI Tests
// ============================================

describe('main', () => {
  // Capture console.log output
  /** @type {string[]} */
  let consoleOutput = [];
  const originalLog = console.log;

  before(() => {
    console.log = (...args) => consoleOutput.push(args.join(' '));
  });

  after(() => {
    console.log = originalLog;
  });

  beforeEach(() => {
    consoleOutput = [];
  });

  it('returns 0 on success', async () => {
    const exitCode = await main([FIXTURES_DIR]);
    assert.equal(exitCode, 0);
  });

  it('outputs markdown by default', async () => {
    await main([FIXTURES_DIR]);
    const output = consoleOutput.join('\n');
    assert.ok(output.includes('# API Discovery Report'));
  });

  it('outputs JSON with --format json', async () => {
    await main([FIXTURES_DIR, '--format', 'json']);
    const output = consoleOutput.join('\n');
    const parsed = JSON.parse(output);
    assert.ok(parsed.specs);
    assert.ok(parsed.summary);
  });

  it('prints help with --help', async () => {
    const exitCode = await main(['--help']);
    assert.equal(exitCode, 0);
    const output = consoleOutput.join('\n');
    assert.ok(output.includes('AIP OpenAPI Discovery'));
    assert.ok(output.includes('USAGE'));
  });

  it('uses current directory when no path specified', async () => {
    // This will search from cwd, just verify it doesn't crash
    const exitCode = await main([]);
    assert.equal(exitCode, 0);
  });

  it('discovers specs in fixtures directory', async () => {
    await main([FIXTURES_DIR, '--format', 'json']);
    const output = consoleOutput.join('\n');
    const parsed = JSON.parse(output);

    // Should find valid-openapi3.yaml and valid-swagger2.json at minimum
    // (generated-spec.yaml has empty paths so might not be found by glob)
    assert.ok(parsed.specs.length >= 2);

    // Check summary counts
    assert.ok(parsed.summary.openapi3 >= 1);
  });
});
